[package]
name = "nimiq-network-libp2p"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Nimiq network implementation based on libp2p"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs-albatross"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
async-trait = "0.1"
futures = { version = "0.3", features = ["bilock"] }
ip_network = "0.3"
libp2p = "0.34"
log = "0.4"
parking_lot = "0.9"
rand = "0.7.3"
tokio = { version = "0.2", features = ["macros", "rt-core"] }
bytes = "0.6"
pin-project = "1.0"
bitflags = "1.2"
thiserror = "1.0"
hex = "0.4"
wasm-timer = "0.2"
serde = { version = "1.0", features = ["derive"], optional = true }
async-std = "1.7" # Used in some places, but can we not depend on a runtime?

beserial = { path = "../beserial", version = "0.1", features = ["libp2p"] }
beserial_derive = { path = "../beserial/beserial_derive", version = "0.1" }
nimiq-network-interface = { path = "../network-interface", version = "0.1" }
nimiq-keys = { path = "../keys", version = "0.1" }
nimiq-peer-address = { path = "../peer-address", version = "0.1" }
nimiq-macros = { path = "../macros", version = "0.1" }
nimiq-hash = { path = "../hash", version = "0.1" }
nimiq-utils = { path = "../utils", version = "0.1", features = ["tagged-signing", "serde-derive", "libp2p", "time"] }

[dev-dependencies]
env_logger = "0.8"

[features]
default = ["peer-contact-book-persistence"]
peer-contact-book-persistence = ["serde"]
