[package]
name = "nimiq-rpc-server"
version = "0.1.0"
authors = ["The Nimiq Core Development Team <info@nimiq.com>"]
license = "Apache-2.0"
edition = "2018"
description = "JSON RPC server for the Nimiq Rust implementation"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
gitlab = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
travis-ci = { repository = "https://github.com/nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "https://github.com/nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "https://github.com/nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
hyper = "0.12"
json = "0.11"
futures = "0.1"
log = "0.4"
hex = "0.3"
failure = "0.1"
parking_lot = "0.7"
base64 = "0.10"
beserial = { path = "../beserial", version = "0.1.0" }
nimiq-consensus = { path = "../consensus", version = "0.1.0" }
nimiq-blockchain = { path = "../blockchain", version = "0.1.0" }
nimiq-network = { path = "../network", version = "0.1.0" }
nimiq-hash = { path = "../hash", version = "0.1.0" }
nimiq-network-primitives = { path = "../network-primitives", version = "0.1.0" }
nimiq-block = { path = "../primitives/block", version = "0.1.0" }
nimiq-transaction = { path = "../primitives/transaction", version = "0.1.0" }
nimiq-keys = { path = "../keys", version = "0.1.0" }
nimiq-block-production = { path = "../block-production", version = "0.1.0" }
nimiq-utils = { path = "../utils", version = "0.1.0", features = ["merkle", "time"] }
