[package]
name = "nimiq-keys"
version = "0.2.0"
authors = ["Pascal B <git@paberr.net>", "The Nimiq Core Development Team <info@nimiq.com>"]
edition = "2018"
description = "Ed25519 cryptographic key handling and signatures for Nimiq"
homepage = "https://nimiq.com"
repository = "https://github.com/nimiq/core-rs"
license = "Apache-2.0"
categories = ["cryptography::cryptocurrencies"]
keywords = ["nimiq", "cryptocurrency", "blockchain"]

[badges]
travis-ci = { repository = "nimiq/core-rs", branch = "master" }
is-it-maintained-issue-resolution = { repository = "nimiq/core-rs" }
is-it-maintained-open-issues = { repository = "nimiq/core-rs" }
maintenance = { status = "experimental" }

[dependencies]
curve25519-dalek = "1.0.2"
ed25519-dalek = "1.0.0-pre.4"
data-encoding = "2.1"
sha2 = "0.8"
rand = "0.7"
hex = "0.3"
failure = "0.1"
beserial = { path = "../beserial", version = "0.2" }
beserial_derive = { path = "../beserial/beserial_derive", version = "0.2" }
nimiq-hash = { path = "../hash", version = "0.2" }
nimiq-macros = { path = "../macros", version = "0.2" }
